### ISSUE TITLE
as a user, I should be able to use non-github repositories

### ISSUE THREAD

**Issue by mparker17** [oriuminc/vagrant-ariadne#10]
Ariadne assumes that all repositories are stored on Github, which may not be the case for every organization. It would be nice if it would accept full URLs for repositories.

**Comment by patcon** [comment]
+1

**Comment by mparker17** [comment]
On my local repository, I made changes to the releases/1.0.0 repository... I should rebase them onto the develop branch and submit my changes as a pull request.

**Comment by mparker17** [comment]
Oops... I forgot to switch to a new branch before pushing that. :( Fortunately it was on my fork.

Let me try again...
