### ISSUE TITLE
As a developer, I should be able to easily find the code that sets up the demo site.

### ISSUE THREAD

**Issue by mparker17** [oriuminc/vagrant-ariadne#13]
Ariadne comes with the ability to spin up a demo site by running `vagrant up` without specifying a project, but the code that specifies what will happen is not immediately obvious.

There's also a note in the README that states there are no public examples of the format expected for an Ariadne project repo.

These problems could be solved by creating an example project in `cookbooks-projects` to set up the example project. Users new to Ariadne could even potentially use it as a starting point for their own projects.

**Comment by mparker17** [comment]
When I was talking with @patcon today in the office, he pointed out that the cookbook is at `cookbooks-override/ariadne/recipes/example.rb`.

So I really only need to add some documentation saying "hey, go look over there!"

**Comment by patcon** [comment]
Was thinking on this during my jetlag-induced incomnia last night, and realized that it's probably best to treat the example recipe like any other ariadne project cookbook, an store it in `cookbooks-projects` :)

**Comment by patcon** [comment]
This is done :)
https://github.com/myplanetdigital/ariadne/commit/099a25fcfc3500673f15023f9bebacf847e3c6cc#cookbooks-projects
