### ISSUE TITLE
Quick Start Notes

### ISSUE THREAD

**Issue by mgifford** [oriuminc/vagrant-ariadne#20]
Couple small points as I've put hours into trying to get this set up without much luck.

Remind Mac folks that they need XCode's Command Line Tool.

Even if you're not using their GCC apparently it's needed.

I can run vagrant from the command line.  I'm testing with (and there's no problem):

```
vagrant box add lucid32 http://files.vagrantup.com/lucid32.box
```

but unfortunately, when it comes to running the setup:

```
$ rake setup                             # Runs first-time setup commands
```

It's really failing for me.  

```
$  rake setup      
(in /Users/mike/shared/ariadne)
rake aborted!
no such file to load -- vagrant
/Users/mike/shared/ariadne/Rakefile:1:in `require'
(See full trace by running task with --trace)
```

I can't see what's wrong with line 1 of the Rakefile:
    require 'vagrant'

However, I'm not a ruby guy and I'm sure there's stuff I'm just not looking for that I'm doing wrong.

**Comment by patcon** [comment]
Ok, so first off, really appreciate your taking the time to give it a shot. I'm really sorry it didn't go smoothly. Setup troubleshooting is always the hardest, as it's hard to undo everything that's been done to my system, but I'll give it a shot tomorrow! I'm at drupalcon munich, and tomorrow is sprint day, so it's definitely a good opportunity to fix it :)

**Comment by mgifford** [comment]
We didn't make it to DrupalCon this year, had to take a bit of a break, but definitely looking at Portland.

It's always the little things that can get stuck.  Could just be something with how the rake script operates with my bash settings.

Anyways, if you've got any ideas as to how rake could fail that would be good.  It's definitely not simple to set up this (or any) environment like this.  

Hopefully we'll be able to contribute.

**Comment by mgifford** [comment]
Tried looking at this again.  Partly I wonder if the instructions for Vagrant have changed.  It used to be that you'd use gem, but they are now recommending packages.  That being said, if rake can't find it...

So I tried installing it through gem like:

$ gem install vagrant
Building native extensions.  This could take a while...
Fetching: childprocess-0.3.5.gem (100%)
Fetching: json-1.5.4.gem (100%)
Building native extensions.  This could take a while...
Fetching: log4r-1.1.10.gem (100%)
Fetching: net-ssh-2.2.2.gem (100%)
Fetching: net-scp-1.0.4.gem (100%)
Fetching: vagrant-1.0.3.gem (100%)
Successfully installed ffi-1.1.5
Successfully installed childprocess-0.3.5
Successfully installed json-1.5.4
Successfully installed log4r-1.1.10
Successfully installed net-ssh-2.2.2
Successfully installed net-scp-1.0.4
Successfully installed vagrant-1.0.3
7 gems installed
/Users/mike/.rvm/gems/ruby-1.9.3-p194/gems/json-1.7.5/lib/json/ext/parser.bundle: [BUG] Segmentation fault
ruby 1.8.7 (2012-02-08 patchlevel 358) [universal-darwin12.0]

Abort trap: 6

Got this list of what seem to be local gems:

$ gem list

**\* LOCAL GEMS ***

actionmailer (3.2.8)
actionpack (3.2.8)
activemodel (3.2.8)
activerecord (3.2.8)
activeresource (3.2.8)
activesupport (3.2.8)
archive-tar-minitar (0.5.2)
arel (3.0.2)
builder (3.0.0)
bundler (1.2.0, 1.1.5)
childprocess (0.3.5)
erubis (2.7.0)
ffi (1.1.5)
hike (1.2.1)
i18n (0.6.0)
journey (1.0.4)
json (1.7.5, 1.5.4)
log4r (1.1.10)
mail (2.4.4)
mime-types (1.19)
multi_json (1.3.6)
net-scp (1.0.4)
net-ssh (2.2.2)
polyglot (0.3.3)
rack (1.4.1)
rack-cache (1.2)
rack-ssl (1.3.2)
rack-test (0.6.1)
rails (3.2.8)
railties (3.2.8)
rake (0.9.2.2)
rdoc (3.12)
rubygems-bundler (1.0.7)
rvm (1.11.3.5)
sprockets (2.1.3)
thor (0.16.0)
tilt (1.3.3)
treetop (1.4.10)
tzinfo (0.3.33)
vagrant (1.0.3)

Did the upgrade to make sure there wasn't anything obviously missing:

$ sudo gem update rake
Password:
Updating installed gems
Nothing to update

And finally with a trace to try to tack stuff down.

bash-3.2$  rake setup --trace
(in /Users/mike/shared/htdocs/drupal-mydigitalplanet/ariadne)
rake aborted!
no such file to load -- vagrant
/Users/mike/shared/htdocs/drupal-mydigitalplanet/ariadne/Rakefile:1:in `require'
/Users/mike/shared/htdocs/drupal-mydigitalplanet/ariadne/Rakefile:1
/System/Library/Frameworks/Ruby.framework/Versions/1.8/usr/lib/ruby/1.8/rake.rb:2383:in`load'
/System/Library/Frameworks/Ruby.framework/Versions/1.8/usr/lib/ruby/1.8/rake.rb:2383:in `raw_load_rakefile'
/System/Library/Frameworks/Ruby.framework/Versions/1.8/usr/lib/ruby/1.8/rake.rb:2017:in`load_rakefile'
/System/Library/Frameworks/Ruby.framework/Versions/1.8/usr/lib/ruby/1.8/rake.rb:2068:in `standard_exception_handling'
/System/Library/Frameworks/Ruby.framework/Versions/1.8/usr/lib/ruby/1.8/rake.rb:2016:in`load_rakefile'
/System/Library/Frameworks/Ruby.framework/Versions/1.8/usr/lib/ruby/1.8/rake.rb:2000:in `run'
/System/Library/Frameworks/Ruby.framework/Versions/1.8/usr/lib/ruby/1.8/rake.rb:2068:in`standard_exception_handling'
/System/Library/Frameworks/Ruby.framework/Versions/1.8/usr/lib/ruby/1.8/rake.rb:1998:in `run'
/usr/bin/rake:31

Hmm..  I wonder if this is the issue.  I think this is supposed to be ruby 1.9.2 or 1.9.3.  

Maybe I need to find out how to remove the 1.8 reference & upgrade it for Rake?

I also think this might be complicated as I'm running on Mac's Lion.

**Comment by patcon** [comment]
OK, so I'm actually working on getting this working in windows today, so I'm kinda in the "back-to-the-basics" mindset :)

Can I ask if you have rvm installed? if it is, then when you "cd" into the ariadne directory, it should kick off the `.rvmrc` script which does some critical setup. Did that happen? If so, then rake should be installed already.

Let me know man

**Comment by mgifford** [comment]
I've run around this a few times, so I've probably made then broken stuff who knows how many times.  But I just checked:

$ rvm version
rvm 1.15.8 (latest) by Wayne E. Seguin wayneeseguin@gmail.com, Michal Papis mpapis@gmail.com [https://rvm.io/]

From the ariadne directory I get:

$ rvm --install use ruby-${RUBY_VERS}-${RUBY_PATCH} -n ariadne
ruby-1.9.3-p194-ariadne is not installed.
You requested building with '/usr/bin/gcc-4.2' but it is not in your path.
Using /Users/mike/.rvm/gems/ruby-1.9.3-p194-ariadne
Running /Users/mike/.rvm/hooks/after_use

I've hunted around to figure out this gcc issue, but lots of half instructions, many of them contradictory.

And a little later I tried this:

bash-3.2$ rvm install 1.9.3 --with-gcc=clang
clang: error: unsupported option '--with-libyaml'
clang: error: unsupported option '--with-libyaml'
clang: error: unsupported option '--with-libyaml'
Building 'ruby-1.9.3-p194' using clang - but it's not (fully) supported, expect errors.
Installing Ruby from source to: /Users/mike/.rvm/rubies/ruby-1.9.3-p194, this may take a while depending on your cpu(s)...

ruby-1.9.3-p194 - #downloading ruby-1.9.3-p194, this may take a while depending on your connection...
ruby-1.9.3-p194 - #extracting ruby-1.9.3-p194 to /Users/mike/.rvm/src/ruby-1.9.3-p194
ruby-1.9.3-p194 - #extracted to /Users/mike/.rvm/src/ruby-1.9.3-p194
ruby-1.9.3-p194 - #configuring 
ruby-1.9.3-p194 - #compiling 
ruby-1.9.3-p194 - #installing 
Removing old Rubygems files...
Installing rubygems-1.8.24 for ruby-1.9.3-p194 ...
Installation of rubygems completed successfully.
ruby-1.9.3-p194 - adjusting #shebangs for (gem irb erb ri rdoc testrb rake).
ruby-1.9.3-p194 - #importing default gemsets (/Users/mike/.rvm/gemsets/)
Install of ruby-1.9.3-p194 - #complete 
clang: error: unsupported option '--with-libyaml'
Ruby 'ruby-1.9.3-p194' was built using clang - but it's not (fully) supported, expect errors.

bash-3.2$ rake setup  
[BUG] cross-thread violation on rb_gc()
(null)

Abort trap: 6

Which then brought me to:
http://stackoverflow.com/questions/3413209/error-cross-thread-violation-on-rb-gc

I found an old copy of MacPorts that had ruby as well as an older version in /Users/mike/.rvm/src/

After removing those, it seemed to start up.

**Comment by mgifford** [comment]
What a huge thread (for github).

Ok, so I ran into a problem last night with VirtualBox not working.  I restarted the computer and this morning that started up just fine, but rvm was nowhere to be found.  I deleted the ~/.rvm directory & rebuilt it...  It keeps feeling like I'm almost there.  Anyways, I'm here now:

```
$ cd ariadne/
====================================================================================
= NOTICE                                                                           =
====================================================================================
= RVM has encountered a new or modified .rvmrc file in the current directory       =
= This is a shell script and therefore may contain any shell commands.             =
=                                                                                  =
= Examine the contents of this file carefully to be sure the contents are          =
= safe before trusting it! ( Choose v[iew] below to view the contents )            =
====================================================================================
Do you wish to trust this .rvmrc file? (/Users/mike/shared/htdocs/drupal-mydigitalplanet/ariadne/.rvmrc)
y[es], n[o], v[iew], c[ancel]> y
ruby-1.9.3-p194-ariadne is not installed.
Installing Ruby from source to: /Users/mike/.rvm/rubies/ruby-1.9.3-p194-ariadne, this may take a while depending on your cpu(s)...

ruby-1.9.3-p194-ariadne - #downloading ruby-1.9.3-p194, this may take a while depending on your connection...
ruby-1.9.3-p194-ariadne - #extracting ruby-1.9.3-p194 to /Users/mike/.rvm/src/ruby-1.9.3-p194-ariadne
ruby-1.9.3-p194-ariadne - #extracted to /Users/mike/.rvm/src/ruby-1.9.3-p194-ariadne
ruby-1.9.3-p194-ariadne - #configuring 
ruby-1.9.3-p194-ariadne - #compiling 
ruby-1.9.3-p194-ariadne - #installing 
Using /Users/mike/.rvm/gems/ruby-1.9.3-p194-ariadne
Running /Users/mike/.rvm/hooks/after_use
Removing old Rubygems files...
Installing rubygems-1.8.24 for ruby-1.9.3-p194-ariadne ...
Installation of rubygems completed successfully.
ruby-1.9.3-p194-ariadne - adjusting #shebangs for (gem irb erb ri rdoc testrb rake).
ruby-1.9.3-p194-ariadne - #importing default gemsets (/Users/mike/.rvm/gemsets/)
Using /Users/mike/.rvm/gems/ruby-1.9.3-p194-ariadne
Running /Users/mike/.rvm/hooks/after_use
Install of ruby-1.9.3-p194-ariadne - #complete 
Using /Users/mike/.rvm/gems/ruby-1.9.3-p194-ariadne
Running /Users/mike/.rvm/hooks/after_use
Installing Bundler via Rubygems...
Fetching: bundler-1.1.4.gem (100%)
Successfully installed bundler-1.1.4
1 gem installed
Installing bundled gems via Bundler...
Fetching gem metadata from http://rubygems.org/......
Using rake (0.9.2.2) 
Installing archive-tar-minitar (0.5.2) 
Installing bunny (0.7.9) 
Installing erubis (2.7.0) 
Installing highline (1.6.12) 
Installing json (1.5.4) with native extensions 
Installing mixlib-log (1.3.0) 
Installing mixlib-authentication (1.1.4) 
Installing mixlib-cli (1.2.2) 
Installing mixlib-config (1.1.2) 
Installing mixlib-shellout (1.0.0) 
Installing moneta (0.6.0) 
Installing net-ssh (2.2.2) 
Installing net-ssh-gateway (1.1.0) 
Installing net-ssh-multi (1.1) 
Installing ipaddress (0.8.0) 
Installing systemu (2.5.1) 
Installing yajl-ruby (1.1.0) with native extensions 
Installing ohai (6.14.0) 
Installing mime-types (1.18) 
Installing rest-client (1.6.7) 
Installing polyglot (0.3.3) 
Installing treetop (1.4.10) 
Installing uuidtools (2.1.2) 
Installing chef (0.10.10) 
Installing ffi (1.0.11) with native extensions 
Installing childprocess (0.3.2) 
Installing daemons (1.1.8) 
Installing eventmachine (0.12.10) with native extensions 
Installing i18n (0.6.0) 
Installing thor (0.14.6) 
Installing librarian (0.0.20) 
Installing log4r (1.1.10) 
Installing net-scp (1.0.4) 
Installing rexec (1.4.1) 
Installing rubydns (0.3.4) 
Installing vagrant (1.0.3) 
Installing vagrant-dns (0.2.4) 
Installing vagrant-vbguest (0.3.2) 
Using bundler (1.2.0) 
Your bundle is complete! Use `bundle show [gemname]` to see where a bundled gem is installed.
Post-install message from bunny:
[Version 0.7.8] test suite cleanup (eliminated some race conditions related to queue.message_count)

Activating rubygems-bundler...
archive-tar-minitar 0.5.2
bundler 1.2.0
bundler 1.1.4
chef 0.10.10
erubis 2.7.0
json 1.5.4
librarian 0.0.20
ohai 6.14.0
rake 0.9.2.2
rest-client 1.6.7
rexec 1.4.1
rubydns 0.3.4
rubygems-bundler 1.1.0
thor 0.14.6
treetop 1.4.10
vagrant 1.0.3
Running /Users/mike/.rvm/hooks/after_cd


This all looked just great!  However, the next step (I believe) is to call the Vagrantfile with:

$ vagrant up
There was a problem with the configuration of Vagrant. The error message(s)
are printed below:

vm:
* Shared folder host path for 'apt-cache' doesn't exist: /Users/mike/shared/htdocs/drupal-mydigitalplanet/ariadne/tmp/apt/cache
* Shared folder host path for 'html' doesn't exist: /Users/mike/shared/htdocs/drupal-mydigitalplanet/ariadne/data/html
```

I think I shouldn't get the errors below (which I think are bugs in ariadne) but maybe it's because I previously had a Vagrantfile there? I pulled ariadne from git before doing anything this morning.

**Comment by patcon** [comment]
haha I am so confused how everything just started working, but that last message looks like it's going fine!

I think the _only_ thing you missed was running `rake setup` again, as it wasn't actually running any of those other times :)

Maybe try that and rerun `vagrant up`?

**Comment by mgifford** [comment]
Wow..  And yes..  did the rake setup and then

```
$ rake setup
"Installing cookbooks using Librarian gem..."
"Starting vagrant-dns server..."
"(You may be prompted for your system password.)"
"Creating required directories:"
"tmp/apt/cache/partial"
"data/html"
"data/make"
"cookbooks-projects"
```

Seems like I'm away to the races now.

May this thread be a warning about the many ways that one can get this wrong.  :)

**Comment by patcon** [comment]
haha wahoo! Since I should still read through this an fix the readme appropriately, going to reopen until that gets done :)

**Comment by mgifford** [comment]
Another thing I noticed was that after I'd done vagrant up I needed to go into the VirtualBox admin and start the server before I could access the http://example.dev site you'd configured.  That seemed counter intuitive to me. Not sure if that's particular to my set up.  As you know there are some quirks about how I've gone about this.

**Comment by patcon** [comment]
Ah, I imagine you're using `master` branch, which is the default branch that clones. It only has the official tagged releases on it, instead of the oft-changing/breaking, `develop` branch, which has the fix (CTRL-F for `example.rb` to see the file):
https://github.com/myplanetdigital/ariadne/compare/master...develop

Varnish wasn't being restarted :)

I've just merged a new release, 1.1.0, into master, in case you want to pull it (it _should_ be backward compatible, so it should work if you just run through the setup again: rvm script, cd into project dir, run `rake setup`, etc.):
https://github.com/myplanetdigital/ariadne/commit/d6904b5c27faad1ce8c9bd2f75211f8cabda6416

**Comment by mgifford** [comment]
That didn't quite work as plan.  I had to pull down the rvm script again for some reason.  

Also, I'm assuming I need to do git pull to yank down the latest code.  I also hadn't shut down the VirtualBox or done vagrant destroy.  

Anyways, it seems to be starting up again.  The upgrade process should also get worked into the README.  

So a couple things popped up in red.  The "stdin: is not a tty" in:

[ariadne] Running provisioner: Vagrant::Provisioners::Shell...
stdin: is not a tty
Upgrading Chef to 0.10.8...

And later "sh: pear: not found" in:

[Mon, 10 Sep 2012 20:38:26 +0200] INFO: Could not find previously defined grants.sql resource
sh: 
pear: not found

[Mon, 10 Sep 2012 20:38:27 +0200] INFO: Processing package[git-core] action install (git::default line 21)

In the end it is working though after pulling down the new repo.  And Varnish was running (as you'd hope):

root@lucid64:/home/vagrant# /etc/init.d/varnish status
- varnishd is running

**Comment by patcon** [comment]
Haha as I said :)

> (it should be backward compatible, so it should work if you just run through the setup again: **rvm script, cd into project dir, run `rake setup`**, etc.)

At the very least, the version of RVM it was tested on had changed, but I'm guessing the thing that made it work was `cd`ing into the ariadne directory again (the `.rvmrc` file runs automatically and does some setup). If you haven't run `rake setup` again as well, I'd recommend doing that, or else you're working with old cookbooks which are just working by coincidence. But yes, definitely should doc that expectation :)

> So a couple things popped up in red. The "stdin: is not a tty" in:
> 
> ```
> [ariadne] Running provisioner: Vagrant::Provisioners::Shell...
> stdin: is not a tty
> Upgrading Chef to 0.10.8...
> ```

See #14

> And later "sh: pear: not found" in:
> 
> ```
> [Mon, 10 Sep 2012 20:38:26 +0200] INFO: Could not find previously defined grants.sql resource
> sh:
> pear: not found
> ```

See #12

**Comment by patcon** [comment]
Thanks again @mgifford!

**Comment by patcon** [comment]
oh hey, if your rvm command keeps disappearing, it might be that it's not being sourced in your `~/.zshrc` or `~/.bashrc` or `~/.bash_profile` or whatever. Check out the rvm docs to be sure. If it doesn't stick when you open a new shell, then that's likely it.

**Comment by patcon** [comment]
Think I'm just going to take this into account for #41 :)
