### ISSUE TITLE
General feedback from @sylus

### ISSUE THREAD

**Issue by patcon** [oriuminc/vagrant-ariadne#21]
//cc @sylus

Copying this over from another issue thread: wet-boew/wet-boew-drupal#232

Will work through replies during drupalcon sprint day tomorrow, and create sub-issues as appropriate.

> Hey @patcon,
> 
> I actually had a bit of feedback. Some are probably pretty trivial but would like to toss your way. I am not sure how pertinent everything is so just did a quick write up here for now. Please keep in mind most of these things are nice to have and me trying to align with government needs so quite possibly not good recommendations.
> 
> Overall though I love ariadne and really think the work you have done with it is exceptional.
> 
> Points:
> 1. .rvmrc and ruby install can fail in MacOSX (even with command line tools) Not sure why but I kept getting a make compile error having to do with a readline problem and gcc (still not sure what I did to fix it lol!).
> 2. Some documentation on how to extend ariadne would be useful unless we are just supposed to fork it and modify it which also makes sense. :)
> 3. Was worried a bit about performance in the VM and read an issue which you took apart of. Do you maintain it is largely the setup and not the VM itself? I notice xforty/vagrant-drupal uses a few performance settings in their Vagrantfile. Possibly relevant?
>    
>    ```
>    # VirtualBox performance improvements
>    config.vm.customize ["modifyvm", :id, "--nictype1", "virtio"]
>    config.vm.customize ["modifyvm", :id, "--nictype2", "virtio"]
>    config.vm.customize ["storagectl", :id, "--name", "SATA Controller", "--hostiocache", "off"]
>    ```
> 4. I would love if we adapted and integrated the https://github.com/wch/vagrant-ec2-r repo so can do a simply deployment to ec2 without needing chef server. I tested it myself and worked great with their custom cookbooks. Looking at the code it only parses the run_list and converts to json (runs chef -c .... -j dna.json) but would be great to add roles etc. This could be used for users who don't have a capable enough local computer. If we included a step by step on running on a m1.small server could help alot!
> 5. If we could discuss and have a step by step guide on how to use veewee to build custom boxes (RHEL for government) I think that also could help. I know there are some already around but perhaps more tailored to integrating with ariadne.
> 6. A solr cookbook would be a great addition. I'd love to help on this space. We could base off of: https://github.com/theozaurus/chef-solr and modify it to instead support tomcat 7.
> 7. You host alot of the chef recipes yourself, how to they differentiate between opscode hosted ones?
> 8. Windows support would be needed (even though personally would like to ignore) but thinking shouldn't be to hard to use pik for windows? Again I'd love to help in this area.
> 9. More of a future issue but I would LOVE and so would Shared Services Canada if we could find a way to make Vagrant + Chef output in VMDK format so they can simply spool it up. (Think what I just said made sense but don't quote me!)
> 
> Anyways I admit I have entered the devops space rather recently so maybe a lot of my suggestions don't make any sense but thought I would throw them out there. :)
> 
> Overall though I love the modular design and after looking at tons and tons of other repos think ariadne is pretty special! :) I would like to standardize wet-boew-drupal on it. It also doesn't hurt that you guys align with acquia on your setup :)

**Comment by patcon** [comment]
going to task this out into separate issues

**Comment by patcon** [comment]
Everything is in its own issue except that one question about 3) that I have in bold :)

> 1) .rvmrc and ruby install can fail in MacOSX (even with command line tools) Not sure why but I kept getting a make compile error having to do with a readline problem and gcc (still not sure what I did to fix it lol!).

Created #41 for doing extensive doc'ing
Created #42 for decomposing rvmrc into rake tasks

> 2) Some documentation on how to extend ariadne would be useful unless we are just supposed to fork it and modify it which also makes sense. :)

Created #46 to discuss

> 3) Was worried a bit about performance in the VM and read an issue which you took apart of. Do you maintain it is **largely the setup and not the VM itself**? I notice xforty/vagrant-drupal uses a few performance settings in their Vagrantfile. Possibly relevant?
> 
> ```
> # VirtualBox performance improvements
> config.vm.customize ["modifyvm", :id, "--nictype1", "virtio"]
> config.vm.customize ["modifyvm", :id, "--nictype2", "virtio"]
> config.vm.customize ["storagectl", :id, "--name", "SATA Controller", "--hostiocache", "off"]
> ```

**How so? Not sure which issue discussion you might be referring to...!**

But as for the @xforty stuff, I just came across that yesterday and its on my radar to investigate their `Vagrantfile` hotness :) See #38

> 4) I would love if we adapted and integrated the https://github.com/wch/vagrant-ec2-r repo so can do a simply deployment to ec2 without needing chef server. I tested it myself and worked great with their custom cookbooks. Looking at the code it only parses the run_list and converts to json (runs chef -c .... -j dna.json) but would be great to add roles etc. This could be used for users who don't have a capable enough local computer. If we included a step by step on running on a m1.small server could help alot!

Created #44 about ability to deploy to dedicated server

> 5) If we could discuss and have a step by step guide on how to use veewee to build custom boxes (RHEL for government) I think that also could help. I know there are some already around but perhaps more tailored to integrating with ariadne.

Let's lump this in with docs #41

> 6) A **solr cookbook** would be a great addition. I'd love to help on this space. We could base off of: https://github.com/theozaurus/chef-solr and modify it to instead support tomcat 7.

Working on this for the next release of ariadne :) See #32

> 7) You host alot of the chef recipes yourself, how to they differentiate between opscode hosted ones?

Created #43

> 8) Windows support would be needed (even though personally would like to ignore) but thinking shouldn't be to hard to use pik for windows? Again I'd love to help in this area.

Created #24

> 9) More of a future issue but I would LOVE and so would Shared Services Canada if we could find a way to make Vagrant + Chef output in VMDK format so they can simply spool it up. (Think what I just said made sense but don't quote me!)

Create #45, as more discussion needs to happen

**Comment by patcon** [comment]
Resolved concern with #3 elsewhere

**Comment by sylus** [comment]
Awesome amazing work @patcon :)

Will follow all of the sub issues :)
