### ISSUE TITLE
Install webgrind frontend for easy xdebugging

### ISSUE THREAD

**Issue by patcon** [oriuminc/vagrant-ariadne#30]
http://code.google.com/p/webgrind/

Also document in lieu of #29

**Comment by mparker17** [comment]
Webgrind has apparently moved from Google Code to Github: https://github.com/jokkedk/webgrind

**Comment by patcon** [comment]
:+1: thanks!

**Comment by patcon** [comment]
Looks like there aren't any cookbooks out there. It's pretty simple to install, but still... I'm going to create a simple one modeled after this:

https://github.com/r8/vagrant-lamp/blob/master/cookbooks/vagrant_main/recipes/default.rb#L76-88

**Comment by patcon** [comment]
Sounds like there's a way to use this lib to generate visuals:
http://code.google.com/p/jrfonseca/wiki/Gprof2Dot

Needs investigation
