### ISSUE TITLE
Need to restart terminal application after installing rvm on a brand new machine

### ISSUE THREAD

**Issue by darkoantic** [oriuminc/vagrant-ariadne#70]
This is not a project issue per se, but more like an advice if someone gets into the same situation. 
On a brand new machine running OS X 10.8 (Mountain Lion) after installing RVM the shell(s) were unaware of it until I restarted iTerm. rvm reload or opening a new terminal window for some reason didn't work. Quitting and reopening the app did it though.

**Comment by patcon** [comment]
Thanks @darkoantic! @mparker17 had independently realized that `rvm reload` only worked when upgrading rvm, not on first install. But I can't think of any reason why `exec $SHELL` wouldn't work, as it should work just the same as opening a new shell -- correct me if I'm wrong. This is reflected in the `develop` branch README:
https://github.com/myplanetdigital/ariadne/tree/develop#requirements

(As for having to totally restart iterm, I'll need to investigate when I set up the next workstation, but I can't understand why that would be necessary -- every window should be a new session that runs all the `.bashrc` and `.bash_profile` etc stuff :)

Thanks again man!

EDIT: ah. Just realized you must've seen the new README and closed this... meh
