### ISSUE TITLE
More Ubuntu dependencies

### ISSUE THREAD

**Issue by mparker17** [oriuminc/vagrant-ariadne#72]
When setting up Ariadne on my new Ubuntu 12.10 installation, I discovered that I needed to install the following packages before ruby and/or all the required gems would successfully download and install:
- `autoconf` (tested version 2.69-1ubuntu1; package has existed since hardy)
- `libxml2-dev` (tested version 2.8.0+dfsg1-5ubuntu2; since hardy)
- `libxslt1-dev` (tested version 1.1.26-14; since hardy)
- `libyaml-0-2` (tested version 0.1.4-2build1; since lucid)
- `ruby-libxml` (tested version 2.3.2-1; since precise)

I feel like some of these packages were listed in the README before, but I'm going to have to look through the commits and run git-bisect until I can figure out when they were removed.

**Comment by patcon** [comment]
Some of those (`libzslt1-dev` for example), should be dependencies of other packages installed, according to `apt-rdepends`. Might vary based on platform version.

If you wouldn't mind, please leave the build numbers out of the readme, as an `apt-get update && apt-get upgrade` should get people the freshest anyhow. I'd like to reduce the noise in that respect. People are going to want to copy-paste, so can we just keep it to the `apt-get install ...` commands they'll need to run?

**Comment by mparker17** [comment]
> Some of those (libzslt1-dev for example), should be dependencies of other packages installed, according to apt-rdepends. Might vary based on platform version.

It must depend on platform version, because they weren't installed automatically when I installed the packages listed in the README.

> If you wouldn't mind, please leave the build numbers out of the readme, as an apt-get update && apt-get upgrade should get people the freshest anyhow. I'd like to reduce the noise in that respect. If you wouldn't mind, please leave the build numbers out of the readme, as an apt-get update && apt-get upgrade should get people the freshest anyhow. I'd like to reduce the noise in that respect. 

Different distributions have different package installation tools besides `apt-get` (`yum`, `rpm`, `emerge`, etc.), and different package names. _However_, most packaging system version numbers, including Ubuntu's, start with the version numbers of the software they're installing (i.e.: the version number of the package that installs php 5.2 would start with `5.2`), so I included the lowest-tested version numbers to make it easier for someone using a different distribution to extrapolate which packages they would need.

I can be convinced that it's unreasonable to include exact instructions for every distribution; but if it's easy to reduce the work for people with non-Ubuntu distributions, I think it's worth it.

As a weaker argument, I think it would be safe to assume that most Linux users trying to use Vagrant-Ariadne would be able to look at a list of package names and versions and know what to do with them.

**Comment by patcon** [comment]
I've just done a lot of tutorials, and never before seen them listed out -- just `apt-get install` instructions. It's not even a convention widely used in any chef recipes I've seen, official or otherwise, and those are often written by and for sysadmins :)
